language: node_js
node_js:
- node
- "--lts"
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn build -- -p
- yarn lint
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: demo
  github_token:
    secure: neOTg3wOcFR8W/H07qm6AtJtjyv1ov2nXqfpELD44trHWu6NLfDZgm6s87/HuNZS53uViMOG8kGlHeFv3ZpZFzVv1L5D3RDGFn6l9Dkkh7F0AhaOWmZea44VPXgwsZGOlpsX7yX0lJh61p5rpVz/yucbV2rRcICbDc3lssfAkF1+UgrMWkVc/RdOn2BcQ+XgWt5hT3n4zZw2yelgfBTsf0yVGI1YaKj/mBgrf3yYNMFbKQuIt899HY3pBaBtCHmWRL8D3nc/lQCBG7dNusXr+gMF7hg61Be5NWuVcRh4mJipcjJS/RNg6CXsSpjuN/TjIJx6IKom+naQol51IzQJMXwTMF3H8Xtqu09RcmTMRBR0HpYwyHDsMzOs3OaSxRRCeiSz0iGLAGCKbZNHF2zA2jH5tdw5AoARPdRWsKsnOZSN+QERkcUkNLRTm2P8VzJyTfofJNwJsUYzrldAAAyvYrKK4VHMkiCdeu+eWfVbxEcpDt923TEdyTrsd9vSo4GZyN1hX3Zi+pvexBClADNx5FsF8nn+yblG3HFQA+GnD2LulkWfNzB2+n7fMNmov5qFY5AUJvk7erF2GnM9ap3Ttvgxg3KTBLeRdYvu27cLDZT3Vp/SsEaxURESrKNhYiX6OoTxOlHD1017nXqHOaYiLCELvjH41VR3+SRLyFvp+tA=
  on:
    branch: master
